volumes:
  NEXTCLOUD_DB:
  NEXTCLOUD_APP:
  NEXTCLOUD_DATA:
  document_log:

services:
  nextcloud_db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - NEXTCLOUD_DB:/var/lib/mysql
      # - ${PWD}/NEXTCLOUD_DB:/var/lib/mysql <-- for bind to local dir
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_app:
    image: nextcloud:fpm
    container_name: nextcloud_app
    restart: always
    links:
      - nextcloud_db
    volumes:
      - NEXTCLOUD_APP:/var/www/html
      # - ${PWD}/NEXTCLOUD_APP:/var/www/html
      - NEXTCLOUD_DATA:/var/www/nextcloud-data
      # - ${PWD}/NEXTCLOUD_DATA:/var/www/nextcloud-data:rw
    environment:
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
      - NEXTCLOUD_DATA_DIR=/var/www/nextcloud-data
    expose:
      - "80"
      - "9000"
    command: php-fpm && chown www-data:www-data /var/www/nextcloud-data -R

  nextcloud_webserver:
    image: nginx
    container_name: nextcloud_webserver
    restart: always
    ports:
      - 9000:80
    links:
      - nextcloud_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ${PWD}/NEXTCLOUD_APP:/var/www/html:z,ro
    volumes_from:
      - NEXTCLOUD_APP
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - "80"
      - "443"
    volumes:
      - NEXTCLOUD_DOC:/var/www/onlyoffice/Data
      # - ${PWD}/NEXTCLOUD_DOC:/var/www/onlyoffice/Data:rw
      - document_log:/var/log/onlyoffice
